Provide component secret to jicofo
Connection to a session fails after setting up a fresh docker installation.

Jicofo failed with:
FATAL ERROR: Jicofo component secret and auth password must be set

so this commit adds 
- JICOFO_COMPONENT_SECRET
in jicofo.environment